loggingLevel=info
loggingColor=false
loggingJson=false
camel.main.modeline=true
camel.jbang.compileWorkDir=.camel-jbang/compile
camel.jbang.download=true
camel.jbang.fresh=false
camel.jbang.health=false
camel.jbang.metrics=false
camel.jbang.console=false
camel.jbang.mcp=false
camel.jbang.openapiUi=false
camel.jbang.verbose=false
camel.jbang.camel-version=4.23.0-SNAPSHOT
camel.jbang.springBootVersion=4.1.1
camel.jbang.quarkusGroupId=io.quarkus.platform
camel.jbang.quarkusVersion=3.39.4
camel.jbang.quarkusExtensionRegistryBaseUri=https\://registry.quarkus.io
camel.jbang.javaVersion=21
camel.jbang.kameletsVersion=4.22.0
camel.main.name=openapi-server
camel.main.routesIncludePattern=file\:openapi-server.camel.yaml
camel.jbang.classpathFiles=stock-api.json,stock.json
camel.component.properties.location=file\:application.properties,file\:./application.properties
dependency=mvn\:org.apache.camel\:camel-kamelet\:4.23.0-SNAPSHOT
dependency=mvn\:org.apache.camel.kamelets\:camel-kamelets\:4.22.0
dependency=mvn\:org.apache.camel\:camel-yaml-dsl\:4.23.0-SNAPSHOT
dependency=mvn\:org.apache.camel\:camel-direct\:4.23.0-SNAPSHOT
dependency=mvn\:org.apache.camel\:camel-core-languages\:4.23.0-SNAPSHOT
dependency=mvn\:org.apache.camel\:camel-jackson\:4.23.0-SNAPSHOT
dependency=mvn\:org.apache.camel\:camel-bean\:4.23.0-SNAPSHOT
dependency=mvn\:org.apache.camel\:camel-jsonpath\:4.23.0-SNAPSHOT
dependency=mvn\:org.apache.camel\:camel-rest\:4.23.0-SNAPSHOT
dependency=mvn\:org.apache.camel\:camel-rest-openapi\:4.23.0-SNAPSHOT
dependency=mvn\:org.apache.camel\:camel-openapi-java\:4.23.0-SNAPSHOT
dependency=mvn\:org.apache.camel\:camel-http\:4.23.0-SNAPSHOT
dependency=mvn\:org.apache.camel\:camel-platform-http\:4.23.0-SNAPSHOT
camel.server.port=8080
dependency=mvn\:org.apache.camel\:camel-platform-http-main\:4.23.0-SNAPSHOT
dependency=mvn\:org.apache.camel\:camel-platform-http-vertx\:4.23.0-SNAPSHOT
